services:
  database:
    image: mysql:5.7
    ports:
      - 3308:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pswd
      MYSQL_DATABASE: recipe
      MYSQL_USER: admin
      MYSQL_PASSWORD: pswd
    container_name: recipe_api_sql